CREATE DATABASE IF NOT EXISTS BlazeBOT;

USE BlazeBOT;

CREATE TABLE COLORS(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	initial_date DATETIME NOT NULL,
    color VARCHAR(300) NOT NULL,
    repeat_time INTEGER NOT NULL
 );

CREATE TABLE WHITES (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    initial_date DATETIME NOT NULL,
    squence INTEGER NOT NULL
);