CREATE DATABASE IF NOT EXISTS BlazeBOT;
USE BlazeBOT;

CREATE TABLE  ROLLETE_COLORS(
	rollete_colors_id SMALLINT AUTO_INCREMENT PRIMARY KEY,
	rollete_date DATETIME NOT NULL,
    rollete_colors VARCHAR(300) NOT NULL
);

