version: "3"
services:
  mysql:
    container_name: BlazeBotDB
    hostname: mysql
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
